sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: azpycli
  password:
    secure: ZXCH7riEOep6u6ccxY3F2/CSKZBdhIEAVNWBuIuArk44zp4t06KsYAw82IAMI/HSZQHxrn4uJcXkPdVLZONCphC5kPL9cdeY54WsLIbgKcRexclo84oBWIUtxAQsfdAn0/DPbpjVFG4Q11z/OJ67QItHlFLYarOsOPd3xphyx7L6YeIgQKhTkuBdzS7+oxbchsNGnYxWH27mzaGOhaY7QsQqzKNChohusZthbWj5/IFwnP2mjeHT3G4Dp8KckqiUtkPSdxxKfbyqxtKw4BvMi0aT/XfcBLUr11Q7uROwhGR5GCIBvJxgYG/bRmxPUCkWPsF1UJDrAwSeBPeDn3Sh/7CPTbXOgoYci8ksSrpafEf28mtF6bsYyaHPKo0ozVTPdf5UE1AxZn5CagD2z5eE3A+DwSmeb0TssdQrWlkoZ+zheyeNLuyrRDFSu0IGw9E8Q5BZb0tDKr79c1TvuKkFv4uSUDmb2aqdsJzrp9VcEtkfih2mWdNYod4t6nl4r5q0AlLjRNf7FTS2LR9FlnAfD+rJhdImJKrPLoTPF7J/u4wqjCC1z/zjNW+26PmtYk4d60/o8+iYVno3HzkiWwvkbDywf0AgGASePG59bLUhi/hmFgicE3BGy19TmIafk1Zjxl7+gI22JjzjSTSF3jww/4mAlsqI3zemIlQKit3cUmg=
  distributions: sdist bdist_wheel
  on:
    tags: true
