[tox]
envlist =
    py310
    py311
    py312
    py313
    py314

[testenv]
whitelist_externals =
    pylint
    flake8
deps =
    build
    twine
commands=
    python ./scripts/license_verify.py
    python -m build --outdir {envtmpdir}/dist
    python -m twine check {envtmpdir}/dist/*
    pylint azdev --rcfile=.pylintrc -r n
    flake8 --statistics --append-config=.flake8 azdev
